name: Release

on:
    push:
        tags:
            - "*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up NDK
              run: |
                  curl -O https://dl.google.com/android/repository/android-ndk-r27d-linux.zip

                  unzip -q android-ndk-r27d-linux.zip

                  echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r27d" >> $GITHUB_ENV

            - name: Compiling powerblockerd
              run: |

                  APP_DAEMON="powerblockerd"
                  BIN_PATH="src/module/system/bin"
                  DAEMON_PATH="$BIN_PATH/$APP_DAEMON"

                  mkdir -p "$BIN_PATH"

                  $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang \
                    "src/$APP_DAEMON.c" \
                    -o "$DAEMON_PATH"

            - name: Packaging Magisk module
              run: |
                  BUILD_DIR="$GITHUB_WORKSPACE/build"
                  ZIP_NAME="lockscreen-powermenu-blocker.zip"
                  ZIP_PATH="$BUILD_DIR/$ZIP_NAME"
                  MODULE_DIR="$GITHUB_WORKSPACE/src/module"

                  mkdir -p "$BUILD_DIR"

                  (
                    cd "$MODULE_DIR"
                    zip -r "$ZIP_PATH" .
                  )

                  echo "ZIP_NAME=$ZIP_PATH" >> "$GITHUB_ENV"

            - name: Create Release
              uses: softprops/action-gh-release@v3
              with:
                  files: ${{ env.ZIP_NAME }}
                  generate_release_notes: true
